### ISSUE TITLE
Device identification

### ISSUE THREAD

**Issue by mishaturnbull** [PeterEmbedded/Hi3518E-IP-Camera#2]
I'm working on what I believe to be a similar camera -- check the repo at https://github.com/UND-ARC/IPCam for what I've done so far.

Just out of curiousity, I'd like to know whether we're working on the same device or not.  Because I was not the one to purchase the device, I unfortunately don't have a concrete model number as it doesn't appear to be anywhere on the camera.  I'm planning on uploading photos soon and was wondering if you could do the same.

Thank you for the info you've pulled from your camera!  

p.s. if it helps, it seems that my camera has `telnet` access on port 10213 and no other ports open by default (except 80/HTTP).

**Comment by PeterEmbedded** [comment]
@mishaturnbull Looking at your repo and pictures I can confirm our devices are NOT the same. Looks like a great project your are undertaking, I wish I had the time to assist you, seems very do-able. Keep up the good work.

**Comment by mishaturnbull** [comment]
Thanks for checking!  I can say for sure that the info you gathered helped me out a lot in finding a starting point for the project.  Feel free to ask if you have any questions for us!
