### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Jan-2005** [PeterEmbedded/Hi3518E-IP-Camera#4]
Is that board was going to be here?

Can you possibly help me?

Feel free to write me a PN

![Z](https://user-images.githubusercontent.com/31730258/88439346-41ac6280-ce0b-11ea-9924-c66264b1b458.jpg)
![z2](https://user-images.githubusercontent.com/31730258/88439347-42dd8f80-ce0b-11ea-856d-4ecf4a359e1f.JPG)
![z3](https://user-images.githubusercontent.com/31730258/88439350-43762600-ce0b-11ea-8af6-5e024d3a827a.JPG)

**Comment by PeterEmbedded** [comment]
I don't really get what the question is but the PCB in your photo is the 2.4GHz WiFi module. The hi1131.

**Comment by Jan-2005** [comment]
> Ich verstehe nicht wirklich, was die Frage ist, aber die Platine auf Ihrem Foto ist das 2,4-GHz-WiFi-Modul. Der hi1131.

This is a clound camera that I want to call over IP. Can i flash them?
